package com.vipusa.booktown.model.enums;

public enum BookCategory {
    CATEGORY_FICTION,
    CATEGORY_NON_FICTION,
    CATEGORY_SCIENCE,
    CATEGORY_HISTORY,
    CATEGORY_BIOGRAPHY,
    CATEGORY_FANTASY,
    CATEGORY_ROMANCE,
    CATEGORY_HORROR,
    CATEGORY_THRILLER,
    CATEGORY_CHILDREN,
    CATEGORY_YOUNG_ADULT,
    CATEGORY_POETRY,
    CATEGORY_SELF_HELP,
    CATEGORY_BUSINESS,
    CATEGORY_TECHNOLOGY,
    CATEGORY_TRAVEL,
    CATEGORY_COOKING,
    CATEGORY_HEALTH,
    CATEGORY_RELIGION,
    CATEGORY_EDUCATION
}
