spring.application.name=booktown
server.port = 8080

# Load sensitive properties from another file
spring.config.import=optional:classpath:application-secrets.properties

# Tell SpringBoot which JDBC driver class to use to connect to the MySQL database.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto =update

